name: "moshaf_app"
version: "1.0.6+14"
publish_to: none
environment:
  sdk: ">=3.4.4 <4.0.0"
description: A new Flutter project.
dependencies:
  audio_service: ^0.18.15
  audioplayers: ^6.0.0
  bloc: ^8.1.2
  connectivity_plus: ^6.0.4
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_analytics: ^11.3.2
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  firebase_remote_config: ^5.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.6.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  package_info_plus: ^8.0.3
  share_plus: ^10.0.0
  url_launcher: ^6.3.1
  video_player: ^2.7.2
dev_dependencies:
  custom_lint: "^0.6.7"
  custom_lint_builder: "^0.6.7"
  flutter_lints: "^4.0.0"
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: "^1.0.5"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
flutter_assets:
  assets_path: assets/images/
  output_path: lib/
  filename: "image_assets.dart"
  field_prefix: null
